import React from 'react';
import { PremiumFooter } from '../sections';
import AdSpace from '../components/AdSpace';
import { AlertTriangle, ShieldAlert, Stethoscope, Info } from 'lucide-react';

const Section: React.FC<{ icon: React.ReactNode; title: string; children: React.ReactNode }> = ({ icon, title, children }) => (
  <div className="bg-white border border-slate-200/80 rounded-3xl p-8 shadow-sm space-y-4">
    <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
      <div className="w-9 h-9 rounded-xl bg-amber-50 flex items-center justify-center text-amber-500 flex-shrink-0">{icon}</div>
      <h2 className="text-lg font-bold text-slate-800">{title}</h2>
    </div>
    <div className="text-slate-600 text-sm leading-relaxed space-y-3">{children}</div>
  </div>
);

const Disclaimer: React.FC = () => (
  <div className="min-h-screen bg-slate-50/50">
    <main className="pt-32 pb-24 px-4 sm:px-6 max-w-4xl mx-auto">
      <div className="mb-10">
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-50 border border-amber-100 text-xs font-bold text-amber-600 tracking-wider uppercase mb-4">Legal</span>
        <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight mb-3">Medical Disclaimer</h1>
        <p className="text-slate-500 text-sm font-medium">Last updated: July 19, 2026 · Please read this carefully before using our platform.</p>
      </div>

      {/* Prominent warning banner */}
      <div className="bg-amber-50 border border-amber-200 rounded-3xl p-6 mb-8 flex gap-4 items-start">
        <AlertTriangle className="text-amber-500 flex-shrink-0 mt-0.5" size={24} />
        <div>
          <h2 className="font-extrabold text-amber-900 text-base mb-1">Important: Not a Medical Device</h2>
          <p className="text-amber-800 text-sm leading-relaxed">
            Medicus Labs™ is an AI-powered educational tool and is <strong>not a licensed medical device</strong>. Reports generated by this platform are not a substitute for professional clinical diagnosis by a licensed dermatologist or physician.
          </p>
        </div>
      </div>

      {/* Ad Space */}
      <div className="my-8 text-center">
        <AdSpace variant="leaderboard" />
      </div>

      <div className="space-y-6">
        <Section icon={<Info size={18} />} title="Purpose of This Platform">
          <p>Medicus Labs™ uses artificial intelligence to assist in identifying potential dermatological conditions from uploaded skin images. The platform is designed for:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Educational awareness about common skin conditions.</li>
            <li>General informational guidance about symptoms and self-care.</li>
            <li>Preliminary screening assistance — <strong>not</strong> clinical diagnosis.</li>
          </ul>
        </Section>

        <Section icon={<Stethoscope size={18} />} title="AI Limitations">
          <p>Our AI model has the following inherent limitations you must understand:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li><strong>Accuracy is not guaranteed.</strong> AI analysis can be incorrect, especially with poor image quality, unusual conditions, or rare presentations.</li>
            <li><strong>No physical examination.</strong> The AI cannot replicate a full dermatological examination, which includes palpation, dermoscopy, and clinical history.</li>
            <li><strong>Not trained on all conditions.</strong> The model is optimised for common conditions and may miss rare or atypical presentations.</li>
            <li><strong>Healthy classification does not mean healthy.</strong> A result of "Healthy Skin" does not rule out an underlying condition requiring clinical evaluation.</li>
          </ul>
        </Section>

        <Section icon={<ShieldAlert size={18} />} title="Emergency Warning">
          <p className="font-semibold text-red-700">If you are experiencing any of the following, seek immediate emergency medical care:</p>
          <ul className="list-disc pl-5 space-y-1.5 text-red-700">
            <li>Rapidly spreading rash with fever or difficulty breathing.</li>
            <li>Severe allergic reaction (anaphylaxis) — swelling of face, lips, or throat.</li>
            <li>Open wounds, skin infections with pus, or signs of sepsis.</li>
            <li>Sudden unexplained skin discolouration with systemic symptoms.</li>
          </ul>
          <p className="mt-2">Do not rely on any AI tool in an emergency. <strong>Call emergency services immediately.</strong></p>
        </Section>

        <Section icon={<Info size={18} />} title="No Doctor-Patient Relationship">
          <p>Use of Medicus Labs™ does not create a doctor-patient relationship between you and the platform, its operators, or any affiliated entities. The information provided by this platform should never replace consultations with qualified medical professionals.</p>
        </Section>

        <Section icon={<AlertTriangle size={18} />} title="Liability Waiver">
          <p>By using this platform, you acknowledge and agree that:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>You use the Service at your own risk.</li>
            <li>Medicus Labs™ is not liable for any medical decisions made based on AI-generated reports.</li>
            <li>You will consult a licensed healthcare provider before beginning any treatment.</li>
            <li>Results are probabilistic estimates and are not clinically validated diagnoses.</li>
          </ul>
          <p>For questions, contact us at <strong>medicuslabs.com@gmail.com</strong>.</p>
        </Section>
      </div>
    </main>
    <PremiumFooter />
  </div>
);

export default Disclaimer;
