import React from 'react';
import { PremiumFooter } from '../sections';
import { FileText, Scale, AlertTriangle, Ban, CheckSquare } from 'lucide-react';

const Section: React.FC<{ icon: React.ReactNode; title: string; children: React.ReactNode }> = ({ icon, title, children }) => (
  <div className="bg-white border border-slate-200/80 rounded-3xl p-8 shadow-sm space-y-4">
    <div className="flex items-center gap-3 pb-3 border-b border-slate-100">
      <div className="w-9 h-9 rounded-xl bg-sky-50 flex items-center justify-center text-sky-500 flex-shrink-0">{icon}</div>
      <h2 className="text-lg font-bold text-slate-800">{title}</h2>
    </div>
    <div className="text-slate-600 text-sm leading-relaxed space-y-3">{children}</div>
  </div>
);

const TermsConditions: React.FC = () => (
  <div className="min-h-screen bg-slate-50/50">
    <main className="pt-32 pb-24 px-4 sm:px-6 max-w-4xl mx-auto">
      <div className="mb-10">
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-sky-50 border border-sky-100 text-xs font-bold text-sky-600 tracking-wider uppercase mb-4">Legal</span>
        <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight mb-3">Terms &amp; Conditions</h1>
        <p className="text-slate-500 text-sm font-medium">Last updated: July 19, 2026 · By using Medicus Labs, you agree to these terms.</p>
      </div>

      <div className="space-y-6">
        <Section icon={<FileText size={18} />} title="1. Acceptance of Terms">
          <p>By accessing or using the Medicus Labs™ platform ("Service"), you agree to be bound by these Terms &amp; Conditions. If you do not agree to any part of these terms, you may not use the Service.</p>
        </Section>

        <Section icon={<Scale size={18} />} title="2. Nature of the Service">
          <p>Medicus Labs™ provides AI-powered dermatological analysis for <strong>informational and educational purposes only</strong>. The Service is not a substitute for professional medical advice, diagnosis, or treatment.</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Results generated by the AI model are probabilistic estimates and may not be accurate.</li>
            <li>You must always consult a licensed dermatologist or qualified healthcare provider before making any medical decisions.</li>
            <li>Medicus Labs™ does not guarantee the accuracy, completeness, or timeliness of any analysis results.</li>
          </ul>
        </Section>

        <Section icon={<CheckSquare size={18} />} title="3. User Responsibilities">
          <ul className="list-disc pl-5 space-y-1.5">
            <li>You must be at least 18 years old, or have parental consent, to use this Service.</li>
            <li>You are responsible for providing accurate patient information and quality images.</li>
            <li>You must not upload images of individuals without their explicit consent.</li>
            <li>You agree not to use the Service for any unlawful, fraudulent, or harmful purpose.</li>
            <li>You must not attempt to reverse-engineer, scrape, or reproduce any part of the platform.</li>
          </ul>
        </Section>

        <Section icon={<AlertTriangle size={18} />} title="4. Limitation of Liability">
          <p>To the maximum extent permitted by applicable law, Medicus Labs™ and its operators shall not be liable for:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Any direct, indirect, incidental, special, or consequential damages arising from the use of the Service.</li>
            <li>Medical decisions, treatments, or outcomes based on AI-generated reports.</li>
            <li>Loss of data, service interruptions, or errors in AI analysis.</li>
            <li>Third-party actions or content linked from the platform.</li>
          </ul>
        </Section>

        <Section icon={<Ban size={18} />} title="5. Prohibited Uses">
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Using the Service to generate fraudulent medical documents.</li>
            <li>Uploading illegal, obscene, or inappropriate content.</li>
            <li>Attempting to compromise the security or integrity of the platform.</li>
            <li>Reselling or redistributing reports without written permission.</li>
          </ul>
        </Section>

        <Section icon={<FileText size={18} />} title="6. Intellectual Property">
          <p>All content, branding, AI models, and software on the Medicus Labs™ platform are the intellectual property of Medicus Labs™ and are protected by applicable copyright and trademark laws. You may not copy, reproduce, or distribute any part of the Service without prior written consent.</p>
        </Section>

        <Section icon={<FileText size={18} />} title="7. Modifications to Terms">
          <p>We reserve the right to update these Terms &amp; Conditions at any time. Changes will be posted on this page with an updated effective date. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          <p>For questions, contact us at <strong>medicuslabs.com@gmail.com</strong>.</p>
        </Section>
      </div>
    </main>
    <PremiumFooter />
  </div>
);

export default TermsConditions;
